services:
  app:
    build: .
    devices:
      - /dev/i2c-2:/dev/i2c-2
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    privileged: true
    environment:
      - DISPLAY=:0
      - SDL_VIDEODRIVER=x11
      - PYTHONUNBUFFERED=1